# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies for Chromium
RUN apt-get update \
    && apt-get install -y chromium curl gnupg --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for Selenium
ENV CHROME_BIN=/usr/bin/chromium
ENV CHROME_PATH=/usr/bin/chromium

# Set work directory
WORKDIR /app

# Copy application files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir mcp selenium webdriver-manager beautifulsoup4 requests python-pptx google-cloud-storage

# Default command
CMD ["python", "server.py"]
